version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://avnadmin:AVNS_KpsP1cXh8l6FirSXTeS@mysql-1e691765-margamvinay.c.aivencloud.com:12569/jobboard
